/*
 * EXTI_MCAL_Config.h
 *
 *  Created on: Oct 11, 2023
 *      Author: Lenovo
 */

#ifndef MCAL_EXTI_DRIVER_EXTI_MCAL_CONFIG_H_
#define MCAL_EXTI_DRIVER_EXTI_MCAL_CONFIG_H_

/*
 * SENSE :
 * 		EXTI_LOW_LEVEL
 * 		EXTI_ANY_LEVEL
 * 		EXTI_FALLING_EDGE
 * 		EXTI_RISING_EDGE
 */
#define EXT_INT0_SENSE	EXTI_FALLING_EDGE
/*
 * SENSE :
 * 		EXTI_LOW_LEVEL
 * 		EXTI_ANY_LEVEL
 * 		EXTI_FALLING_EDGE
 * 		EXTI_RISING_EDGE
 */
#define EXT_INT1_SENSE	EXTI_RISING_EDGE
/*
 * SENSE :
 * 			EXTI_INT2_FALLING_EDGE
 * 			EXTI_INT2_RISING_EDGE
 */
#define EXT_INT2_SENSE	EXTI_INT2_FALLING_EDGE
/*
 * EXTI STATE :
 * 				EXTI_ENABLE
 * 				EXTI_DISABLE
 */
#define EXTI_INT0_STATE		EXTI_ENABLE
#define EXTI_INT1_STATE		EXTI_DISABLE
#define EXTI_INT2_STATE		EXTI_ENABLE

#endif /* MCAL_EXTI_DRIVER_EXTI_MCAL_CONFIG_H_ */
